# Generated by Django 4.2.1 on 2023-06-03 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fantasy_name', models.CharField(max_length=255)),
                ('cuit', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English'), ('portuguese', 'Portuguese')], default='english', max_length=10)),
                ('identification_type', models.CharField(max_length=50)),
                ('identification_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='FuelOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('requested_date', models.DateField()),
                ('operation_code', models.CharField(max_length=6, unique=True)),
                ('expiration_date', models.DateField()),
                ('tractor_fuel_type', models.CharField(choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50)),
                ('backpack_fuel_type', models.CharField(choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50)),
                ('chamber_fuel_type', models.CharField(choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50)),
                ('tractor_liters', models.PositiveIntegerField()),
                ('backpack_liters', models.PositiveIntegerField()),
                ('chamber_liters', models.PositiveIntegerField()),
                ('tractor_liters_to_load', models.IntegerField(default=-1)),
                ('backpack_liters_to_load', models.IntegerField(default=-1)),
                ('chamber_liters_to_load', models.IntegerField(default=-1)),
                ('requires_odometer', models.BooleanField(default=False)),
                ('requires_kilometers', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('in_agreement', models.IntegerField(choices=[(0, 'No agreement'), (1, 'Under negotiation'), (2, 'Agreed')], default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.drivers')),
            ],
        ),
        migrations.CreateModel(
            name='PumpOperators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trailers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Tractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Refuelings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_date', models.DateField(auto_now_add=True)),
                ('edited_date', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, ''), (1, 'Attending'), (2, 'Finished'), (-1, 'Canceled')], default=0)),
                ('tractor_pic', models.ImageField(upload_to='operation_code/tractor')),
                ('backpack_pic', models.ImageField(upload_to='operation_code/backpack')),
                ('chamber_pic', models.ImageField(upload_to='operation_code/chamber')),
                ('tractor_liters', models.PositiveIntegerField(default=0)),
                ('backpack_liters', models.PositiveIntegerField(default=0)),
                ('chamber_liters', models.PositiveIntegerField(default=0)),
                ('tractor_fuel_type', models.CharField(choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50)),
                ('backpack_fuel_type', models.CharField(choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50)),
                ('chamber_fuel_type', models.CharField(choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('kilometers', models.PositiveIntegerField(blank=True, null=True)),
                ('dispatch_note_pic', models.ImageField(upload_to='operation_code/dispatch_note')),
                ('observation_pic', models.ImageField(blank=True, null=True, upload_to='operation_code/others')),
                ('observation', models.CharField(blank=True, max_length=512, null=True)),
                ('fuel_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fuelorders')),
                ('pump_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pumpoperators')),
            ],
        ),
        migrations.AddField(
            model_name='fuelorders',
            name='tractor_plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tractors'),
        ),
        migrations.AddField(
            model_name='fuelorders',
            name='trailer_plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.trailers'),
        ),
    ]
