# Generated by Django 4.2.6 on 2023-10-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracash',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='extracash-documents'),
        ),
    ]
