# Generated by Django 4.2.1 on 2023-06-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_companysocialaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='language',
        ),
    ]
