# Generated by Django 4.2.1 on 2023-06-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_company_options_remove_drivers_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
