# Generated by Django 4.2.1 on 2023-06-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_drivers_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='identification_type',
            field=models.CharField(default='DNI', max_length=50),
        ),
    ]
