# Generated by Django 4.2.1 on 2023-06-21 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fuelorders_cancel_reason_fuelorders_is_canceled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelorders',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 0, 11, 5, 608228)),
        ),
    ]
