# Generated by Django 4.2.1 on 2023-06-21 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_fuelorders_backpack_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelorders',
            options={'verbose_name': 'Fuel Order', 'verbose_name_plural': 'Fuel Orders'},
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 22, 24, 45, 421648)),
        ),
    ]
