# Generated by Django 4.2.1 on 2023-07-05 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_fuelorders_user_creator_fuelorders_user_lastmod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelorders',
            name='backpack_liters_to_load',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='chamber_liters_to_load',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 12, 0, 10, 52, 422728)),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='requested_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 5, 0, 10, 52, 422716)),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='tractor_liters_to_load',
            field=models.IntegerField(default=0),
        ),
    ]
