# Generated by Django 4.2.1 on 2023-07-07 22:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_fuelorders_backpack_liters_to_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelorders',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 14, 22, 52, 50, 568076, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='requested_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
