# Generated by Django 4.2.1 on 2023-07-07 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_fuelorders_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelorders',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 14, 23, 37, 53, 192239, tzinfo=datetime.timezone.utc)),
        ),
    ]
