# Generated by Django 4.2.1 on 2023-07-09 01:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_fuelorders_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='identification_number',
            field=models.CharField(max_length=50, verbose_name='identification_number'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='identification_type',
            field=models.CharField(default='identification_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='backpack_fuel_type',
            field=models.CharField(blank=True, choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50, null=True, verbose_name='backpack_fuel_type'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='backpack_liters',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='backpack_liters'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='backpack_liters_to_load',
            field=models.IntegerField(default=0, verbose_name='backpack_liters_to_load'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='cancel_reason'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='chamber_fuel_type',
            field=models.CharField(blank=True, choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50, null=True, verbose_name='chamber_fuel_type'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='chamber_liters',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='chamber_liters'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='chamber_liters_to_load',
            field=models.IntegerField(default=0, verbose_name='chamber_liters_to_load'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 1, 57, 27, 757006, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='in_agreement',
            field=models.IntegerField(choices=[(0, 'no_agreement'), (1, 'under_negotiation'), (2, 'agreed')], default=0, verbose_name='in_agreement'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='is_blocked'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='is_canceled'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='is_finished'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='requires_kilometers',
            field=models.BooleanField(default=False, verbose_name='requires_kilometers'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='requires_odometer',
            field=models.BooleanField(default=False, verbose_name='requires_odometer'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='tractor_fuel_type',
            field=models.CharField(blank=True, choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50, null=True, verbose_name='tractor_fuel_type'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='tractor_liters',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='tractor_liters'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='tractor_liters_to_load',
            field=models.IntegerField(default=0, verbose_name='tractor_liters_to_load'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='tractor_plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tractors', verbose_name='tractor_plate'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='trailer_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.trailers', verbose_name='trailer_plate'),
        ),
        migrations.AlterField(
            model_name='tractors',
            name='domain',
            field=models.CharField(max_length=15, verbose_name='domain'),
        ),
        migrations.AlterField(
            model_name='trailers',
            name='domain',
            field=models.CharField(max_length=15, verbose_name='domain'),
        ),
    ]
