# Generated by Django 4.2.1 on 2023-07-17 22:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_alter_drivers_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='identification_number',
            field=models.CharField(max_length=50, verbose_name='N° de ID'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='identification_type',
            field=models.CharField(default='Tipo de ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 22, 50, 21, 199185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tractors',
            name='domain',
            field=models.CharField(max_length=15, verbose_name='Dominio'),
        ),
        migrations.AlterField(
            model_name='trailers',
            name='domain',
            field=models.CharField(max_length=15, verbose_name='Dominio'),
        ),
        migrations.CreateModel(
            name='ExtraCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('requested_date', models.DateField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField(default=datetime.datetime(2023, 7, 24, 22, 50, 21, 214616, tzinfo=datetime.timezone.utc))),
                ('is_blocked', models.BooleanField(default=False, verbose_name='is_blocked')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='is_canceled')),
                ('is_finished', models.BooleanField(default=False, verbose_name='is_finished')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='cancel_reason')),
                ('in_agreement', models.IntegerField(choices=[(0, 'no_agreement'), (1, 'under_negotiation'), (2, 'agreed')], default=0, verbose_name='in_agreement')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.drivers')),
                ('user_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracash_created', to=settings.AUTH_USER_MODEL)),
                ('user_lastmod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracash_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ExtraCash Order',
                'verbose_name_plural': 'ExtraCash Orders',
            },
        ),
    ]
