# Generated by Django 4.2.1 on 2023-07-17 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_extracash_cash_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracash',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 23, 14, 50, 71081, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 23, 14, 50, 52462, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='in_agreement',
            field=models.CharField(choices=[('under_negotiation', 'Under Negotiation'), ('no_agreement', 'No Agreement'), ('agreed', 'Agreed')], default='under_negotiation', max_length=20, verbose_name='in_agreement'),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
