# Generated by Django 4.2.1 on 2023-07-24 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_extracash_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracash',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='extracash',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='fuelorders',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='fuelorders',
            name='is_canceled',
        ),
        migrations.AddField(
            model_name='extracash',
            name='is_pauseed',
            field=models.BooleanField(default=False, verbose_name='is_pauseed'),
        ),
        migrations.AddField(
            model_name='extracash',
            name='pause_reason',
            field=models.TextField(blank=True, null=True, verbose_name='pause_reason'),
        ),
        migrations.AddField(
            model_name='fuelorders',
            name='is_pauseed',
            field=models.BooleanField(default=False, verbose_name='is_pauseed'),
        ),
        migrations.AddField(
            model_name='fuelorders',
            name='pause_reason',
            field=models.TextField(blank=True, null=True, verbose_name='pause_reason'),
        ),
        migrations.AlterField(
            model_name='extracash',
            name='cash_amount',
            field=models.PositiveIntegerField(verbose_name='cash_amount'),
        ),
        migrations.AlterField(
            model_name='extracash',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 31, 1, 5, 58, 854716, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 31, 1, 5, 58, 839112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refuelings',
            name='status',
            field=models.IntegerField(choices=[(0, ''), (1, 'Attending'), (2, 'Finished'), (-1, 'Pauseed')], default=0),
        ),
    ]
