# Generated by Django 4.2.1 on 2023-07-30 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_extracash_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracash',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 4, 24, 25, 482127, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 4, 24, 25, 480376, tzinfo=datetime.timezone.utc)),
        ),
    ]
