# Generated by Django 4.2.1 on 2023-07-30 04:36

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_extracash_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracash',
            name='expiration_date',
            field=models.DateField(default=app.models.get_default_expiration_date),
        ),
        migrations.AlterField(
            model_name='fuelorders',
            name='expiration_date',
            field=models.DateField(default=app.models.get_default_expiration_date),
        ),
    ]
