# Generated by Django 4.2.1 on 2023-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_fuelorders_user_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelorders',
            name='in_agreement',
            field=models.CharField(choices=[('no_agreement', 'Sin acuerdo'), ('under_negotiation', 'En negociación'), ('agreed', 'Acordado')], default='under_negotiation', max_length=20, verbose_name='in_agreement'),
        ),
    ]
