# Generated by Django 4.2.1 on 2023-08-03 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0035_remove_refuelings_fuel_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refuelings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_date', models.DateField(auto_now_add=True)),
                ('edited_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('finished', 'Finished'), ('locked', 'Locked')], default='pending', max_length=10)),
                ('tractor_pic', models.ImageField(upload_to='operation_code/tractor')),
                ('backpack_pic', models.ImageField(upload_to='operation_code/backpack')),
                ('chamber_pic', models.ImageField(upload_to='operation_code/chamber')),
                ('tractor_liters', models.PositiveIntegerField(default=0)),
                ('backpack_liters', models.PositiveIntegerField(default=0)),
                ('chamber_liters', models.PositiveIntegerField(default=0)),
                ('tractor_fuel_type', models.CharField(choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50)),
                ('backpack_fuel_type', models.CharField(choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50)),
                ('chamber_fuel_type', models.CharField(choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50)),
                ('dispatch_note_pic', models.ImageField(upload_to='operation_code/dispatch_note')),
                ('observation_pic', models.ImageField(blank=True, null=True, upload_to='operation_code/others')),
                ('observation', models.CharField(blank=True, max_length=512, null=True)),
                ('fuel_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fuelorders')),
                ('pump_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.pumpoperator')),
            ],
        ),
    ]
