# Generated by Django 4.2.1 on 2023-09-13 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portal.custom_storage
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refuelings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_date', models.DateField(auto_now_add=True)),
                ('edited_date', models.DateField(auto_now=True)),
                ('tractor_pic', models.ImageField(blank=True, null=True, storage=portal.custom_storage.DocumentStorage(), upload_to=staff.models.get_filename)),
                ('backpack_pic', models.ImageField(blank=True, null=True, storage=portal.custom_storage.DocumentStorage(), upload_to=staff.models.get_filename)),
                ('chamber_pic', models.ImageField(blank=True, null=True, storage=portal.custom_storage.DocumentStorage(), upload_to=staff.models.get_filename)),
                ('tractor_liters', models.PositiveIntegerField(default=0)),
                ('backpack_liters', models.PositiveIntegerField(default=0)),
                ('chamber_liters', models.PositiveIntegerField(default=0)),
                ('tractor_fuel_type', models.CharField(blank=True, choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50, null=True)),
                ('backpack_fuel_type', models.CharField(blank=True, choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50, null=True)),
                ('chamber_fuel_type', models.CharField(blank=True, choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50, null=True)),
                ('dispatch_note_pic', models.ImageField(blank=True, null=True, storage=portal.custom_storage.DocumentStorage(), upload_to=staff.models.get_filename)),
                ('observation_pic', models.ImageField(blank=True, null=True, storage=portal.custom_storage.DocumentStorage(), upload_to=staff.models.get_filename)),
                ('observation', models.CharField(blank=True, max_length=512, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('fuel_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.fuelorders')),
                ('pump_operator', models.ForeignKey(limit_choices_to={'groups__name': 'Pump Operators'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
