# Generated by Django 4.2.1 on 2023-09-14 17:45

from django.db import migrations, models
import django.db.models.deletion
import portal.custom_storage
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refuelings',
            name='backpack_pic',
        ),
        migrations.RemoveField(
            model_name='refuelings',
            name='chamber_pic',
        ),
        migrations.RemoveField(
            model_name='refuelings',
            name='dispatch_note_pic',
        ),
        migrations.RemoveField(
            model_name='refuelings',
            name='observation_pic',
        ),
        migrations.RemoveField(
            model_name='refuelings',
            name='tractor_pic',
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('filename', models.ImageField(storage=portal.custom_storage.DocumentStorage(), upload_to=staff.models.get_filename)),
                ('refueling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.refuelings')),
            ],
        ),
    ]
