# Generated by Django 4.2.1 on 2023-08-06 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0003_alter_refuelings_pump_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuelings',
            name='pump_operator',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Pump Operators'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
