# Generated by Django 4.2.1 on 2023-08-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_refuelings_pump_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refuelings',
            name='status',
        ),
        migrations.AddField(
            model_name='refuelings',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refuelings',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
