# Generated by Django 4.2.1 on 2023-08-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_refuelings_fuel_order_and_more'),
        ('staff', '0005_remove_refuelings_status_refuelings_is_finished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refuelings',
            name='is_locked',
        ),
        migrations.AlterField(
            model_name='refuelings',
            name='fuel_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.fuelorders'),
        ),
    ]
