# Generated by Django 4.2.1 on 2023-08-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_refuelings_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuelings',
            name='backpack_pic',
            field=models.ImageField(blank=True, null=True, upload_to='operation_code/backpack'),
        ),
        migrations.AlterField(
            model_name='refuelings',
            name='chamber_pic',
            field=models.ImageField(blank=True, null=True, upload_to='operation_code/chamber'),
        ),
        migrations.AlterField(
            model_name='refuelings',
            name='dispatch_note_pic',
            field=models.ImageField(blank=True, null=True, upload_to='operation_code/dispatch_note'),
        ),
        migrations.AlterField(
            model_name='refuelings',
            name='tractor_pic',
            field=models.ImageField(blank=True, null=True, upload_to='operation_code/tractor'),
        ),
    ]
