# Generated by Django 4.2.1 on 2023-08-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_refuelings_backpack_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuelings',
            name='backpack_fuel_type',
            field=models.CharField(blank=True, choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='refuelings',
            name='chamber_fuel_type',
            field=models.CharField(blank=True, choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='refuelings',
            name='tractor_fuel_type',
            field=models.CharField(blank=True, choices=[('infinia_diesel', 'Infinia Diesel'), ('infinia', 'Infinia'), ('diesel_500', 'Diesel 500'), ('super', 'Super')], max_length=50, null=True),
        ),
    ]
