# Generated by Django 4.2.1 on 2023-08-16 01:07

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_refuelings_backpack_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuelings',
            name='backpack_pic',
            field=models.ImageField(blank=True, null=True, upload_to=staff.models.rename_upload_file),
        ),
        migrations.AlterField(
            model_name='refuelings',
            name='chamber_pic',
            field=models.ImageField(blank=True, null=True, upload_to=staff.models.rename_upload_file),
        ),
        migrations.AlterField(
            model_name='refuelings',
            name='tractor_pic',
            field=models.ImageField(blank=True, null=True, upload_to=staff.models.rename_upload_file),
        ),
    ]
