# Generated by Django 4.2.1 on 2023-08-27 16:07

from django.db import migrations, models
import portal.custom_storage
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_refuelings_backpack_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuelings',
            name='backpack_pic',
            field=models.ImageField(blank=True, null=True, storage=portal.custom_storage.DocumentStorage(), upload_to=staff.models.rename_upload_file),
        ),
        migrations.AlterField(
            model_name='refuelings',
            name='chamber_pic',
            field=models.ImageField(blank=True, null=True, storage=portal.custom_storage.DocumentStorage(), upload_to=staff.models.rename_upload_file),
        ),
        migrations.AlterField(
            model_name='refuelings',
            name='tractor_pic',
            field=models.ImageField(blank=True, null=True, storage=portal.custom_storage.DocumentStorage(), upload_to=staff.models.rename_upload_file),
        ),
    ]
