name: djang-kmportal Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: echo "SSH connection successful."


  kill-servers:
    runs-on: ubuntu-latest
    needs: test-ssh
    steps:
      - uses: actions/checkout@v2
      - name: Kill any server still running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: sudo fuser -k 8080/tcp
        continue-on-error: true

  create-tmux-session:
    runs-on: ubuntu-latest
    needs: test-ssh
    steps:
      - uses: actions/checkout@v2
      - name: Create and rename tmux session
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            tmux kill-session -t django || true
            tmux new-session -A -s django

  git-commands:
    runs-on: ubuntu-latest
    needs: test-ssh
    steps:
      - uses: actions/checkout@v2
      - name: Git commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/
            git fetch origin main
            git reset --hard origin/main

  pip-commands:
    needs: git-commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pip commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/
            pip install --upgrade pip
            pip install -r requirements.txt

  run-migrations:
    needs: pip-commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Django migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/portal/
            python3 manage.py makemigrations
            python3 manage.py migrate

  collect-statics:
    needs: pip-commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Collect static files and set permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/portal/
            python3 manage.py collectstatic --no-input
            sudo chown -R www-data: /home/ubuntu/app/local-cdn/static/

  start-gunicorn:
    needs: 
      - kill-servers
      - run-migrations
      - collect-statics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Gunicorn
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            tmux send-keys -t django 'cd /home/ubuntu/app/portal/ && gunicorn portal.wsgi:application --bind 0.0.0.0:8080 --workers 4' C-m
