name: djang-kmportal Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute commands over ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # add log line
          echo "$(date) - Deploy triggered by ${{ github.actor }} on commit ${{ github.sha }} of ${{ github.repository }}" >> /home/ubuntu/logs/django-kmportal.log

          # update the repo
          cd /home/ubuntu/django-kmportal/
          git pull origin main

          # update pip packages
          pip install --upgrade pip && pip install -r requirements.txt

          # add log line
          echo "$(date) - Update completed :)\n" >> /home/ubuntu/logs/django-kmportal.log


          
