name: djang-kmportal Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute commands over ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # add log line
          echo "$(date) - Deploy triggered by ${{ github.actor }} on commit ${{ github.sha }} of ${{ github.repository }}" >> /home/ubuntu/logs/django-kmportal.log

          # update the repo
          cd /home/ubuntu/django-kmportal/
          git pull origin main

          # update pip packages
          echo "---- $(date) ----" > /home/ubuntu/logs/pip.log
          pip install --upgrade pip >> /home/ubuntu/logs/pip.log 2>&1
          pip install -r requirements.txt >> /home/ubuntu/logs/pip.log 2>&1
          echo "---- $(date) ----" >> /home/ubuntu/logs/pip.log

          # makemigrations and migrate
          echo "---- $(date) ----" >> /home/ubuntu/logs/migrations.log
          python3 portal/manage.py makemigrations >> /home/ubuntu/logs/migrations.log 2>&1
          python3 portal/manage.py migrate >> /home/ubuntu/logs/migrations.log 2>&1

          # add log line
          echo "$(date) - Update completed :)" >> /home/ubuntu/logs/django-kmportal.log

    - name: Restart script in tmux session
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # stop running session if exists
          tmux kill-session -t django-kmportal || true
          
          # start new session
          cd /home/ubuntu/django-kmportal/
          tmux new-session -d -s django-kmportal './portal/runserver.sh'
